# Documentation: https://kubernetes.io/docs/concepts/workloads/pods/pod/
# This is a simple pod file that creates a pod with an Apache web server.
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache
spec:
  containers:
  - name: apache-container
    image: httpd:2.4
    ports:
    - containerPort: 80
    env:
    - name: MY_VARIABLE
      value: "my value"
    - name: ANOTHER_VARIABLE
      value: "another value"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3