# Documentation: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
# This is a simple statefulset file that creates a statefulset with 3 replicas of an Apache web server.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-statefulset
spec:
  serviceName: "apache"
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd:2.4
        ports:
        - containerPort: 80
        env:
        - name: MY_VARIABLE
          value: "my value"
        - name: ANOTHER_VARIABLE
          value: "another value"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"